version = 0.1

[default.deploy.parameters]
stack_name = "amigo-backend"
resolve_s3 = true
s3_prefix = "amigo-backend"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"amigo\""
image_repositories = []

[default.global.parameters]
region = "ap-southeast-2"
